### ISSUE TITLE
Bluetooth 4.0 LE compatibility?

### ISSUE THREAD

**Issue by dlenski** [lwfinger/rtl8723au_bt#17]
As far as I know, the Realtek 8723 hardware is capable of [Bluetooth 4.0 Low Energy/Bluetooth Smart](http://en.wikipedia.org/wiki/Bluetooth_low_energy) mode.

I haven't been able to figure out for sure whether or not this driver supports this operation by playing around with `hcitool lescan` or grepping for LE/4.0/Smart in the code... perhaps this is not something that needs to be implemented in a device-specific driver?

**Comment by lwfinger** [comment]
FYI, there is a new 'kernel' branch that has code that will be in kernel 3.21. It handles the Realtek devices just like any other kernel device. Thus far, no changes for older kernels have been included. As problems are reported, I will fix them.
